// <auto-generated />
namespace SoDelivery.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedNames));
        
        string IMigrationMetadata.Id
        {
            get { return "202011291625543_changedNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
